# # Site settings
# title: Denis Tyurkov
# # email: your-email@domain.com
# # description: > # this means to ignore newlines until "baseurl:"
# #   Write an awesome description for your new site here. You can edit this
# #   line in _config.yml. It will appear in your document head meta (for
# #   Google search results) and in your feed.xml site description.
# baseurl: "/blog" # the subpath of your site, e.g. /blog/
# url: "http://denistyurkov.github.io" # the base hostname & protocol for your site
# # twitter_username: jekyllrb
# # github_username:  jekyll

# # Build settings
# markdown: kramdown


title: "Denis Tyur'kov"
description: "I write about entrepreneurship, self-development, and workouts."

url: "http://localhost:4000"
# url: "http://http://denistyurkov.github.io/blog.html"
baseurl: "/blog.html"

paginate: 10

markdown: rdiscount
permalink: pretty
pygments: true